name: Rust

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu-build:

    runs-on: ubuntu-latest
        
    steps:
    - name: Clone repo
      uses: actions/checkout@v4
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest # Or a specific version like '14'
        platform: x64 # Or 'x86' for 32-bit builds
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  # windows-build:

  #   runs-on: windows-latest

  #   steps:
  #   - name: Clone repo
  #     uses: actions/checkout@v4
  #   - name: Build
  #     run: cargo build --verbose
  #   - name: Run tests
  #     run: cargo test --verbose
