name: Rust

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu-build:

    runs-on: ubuntu-latest
        
    steps:
    - name: Clone repo
      uses: actions/checkout@v4
    - name: Cache APT packages
      uses: awalsh128/cache-apt-pkgs-action@v1.4
      with:
        packages: |
          clang
          libclang-dev
          libopencv-dev
          pkg-config
        version: v1.0 # Optional: Specify a version for cache invalidation
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  # windows-build:

  #   runs-on: windows-latest

  #   steps:
  #   - name: Clone repo
  #     uses: actions/checkout@v4
  #   - name: Build
  #     run: cargo build --verbose
  #   - name: Run tests
  #     run: cargo test --verbose
